import tkinter as tk

root = tk.Tk()
S = tk.Scrollbar(root)
T = tk.Text(root, height=15, width=200)
S.pack(side=tk.RIGHT, fill=tk.Y)
T.pack(side=tk.LEFT, fill=tk.Y)
S.config(command=T.yview)
T.config(yscrollcommand=S.set)
quote = """Prosseguindo...
"('Aula 06 - Matrizes e Vetores')\n").pack_configure()
"('Declarando uma matriz com listas')\n").pack_configure()
"('para isso utilizamos a seguinte nomenclatura')\n").pack_configure()
"('a = input()')\n").pack_configure()
"('print([a])')\n").pack_configure()
"('o indice do primeiro num es 0')\n").pack_configure()

"('criando matriz 3x4 onde cada (i,j) tem valor de ixj, com lacos, repetido i vezes')\n").pack_configure()
"##coloca valores em matriz\n").pack_configure()
"('Ex.18')\n").pack_configure()
"a = int(input('digite valor1: '))\n").pack_configure()
"for i in range(a):\n").pack_configure()
"    b = int(input('digite valor2: '))\n").pack_configure()
"    for j in range(b):\n").pack_configure()
"        c = i*j\n").pack_configure()
"        print(c)\n").pack_configure()

"('Acessando dados em listas')\n").pack_configure()
"('pode-se usar 1 elem específico da matriz')\n").pack_configure()
"('Ex19.: matriz 4x5 iniciando com zeros e lista(0), damos 67 na lista 2 e posição 2')\n").pack_configure()
"M = [[i*j for j in range(4)] for i in range(5)]\n").pack_configure()
"M[2][2] = 67\n").pack_configure()
"print(M)\n").pack_configure()

"('OBS.: a matriz implementada em listas tem indice na posicao 1')\n").pack_configure()
"()\n").pack_configure()
"('Acessando Matrizes')\n").pack_configure()
"('Imprime elem da posicao (2,3) da matriz anterior')\n").pack_configure()
"('Ex.19:Acessando posicao (2,4) da matriz')\n").pack_configure()
"M = [[i*j for j in range(5)] for i in range(5)]\n").pack_configure()
"print(M)\n").pack_configure()
"print(M[2][3])\n").pack_configure()
"N = [[i*j for j in range(5)] for i in range(5)]\n").pack_configure()
"print(N)\n").pack_configure()
"print(N[2][4])\n").pack_configure()

"('Declarando Vetores Multidimensionais')\n").pack_configure()
"('Para criar vetores V1 x V2 x ...x Vi... usamos compressao de listas')\n").pack_configure()
"('[[...for j in range(n)] for i in range(m)...]]')\n").pack_configure()
"('Ex.20')\n").pack_configure()
"a = int(input('digite valor1: '))\n").pack_configure()
"b = int(input('digite valor2: '))\n").pack_configure()
"M = [[i+j for j in range(a)] for i in range(b)]\n").pack_configure()
"print(M)\n").pack_configure()
"##Fim da Aula 6 Matrizes e Vetores##\n").pack_configure()
"""
T.insert(tk.END, quote)
tk.mainloop()
