import tkinter as tk

root = tk.Tk()
S = tk.Scrollbar(root)
T = tk.Text(root, height=15, width=200)
S.pack(side=tk.RIGHT, fill=tk.Y)
T.pack(side=tk.LEFT, fill=tk.Y)
S.config(command=T.yview)
T.config(yscrollcommand=S.set)
quote = """Prosseguindo...
'print("Aula 08 - Modulos no Python")\n')
'print("Nessa parte da programacao, veremos como trabalhar com Documentos Python")\n')
'print("Vejamos un exemplo: Escrever um arquivo")\n')

'print("Teste de abertura de arquivos em Python:")\n')
'print("Tentando abrir um arquivo de texto armazenado no PC:")\n')
'arq = open("arquivo.txt","r")\n')
'for linha in arq:\n')
'    linha = linha.rstrip()\n')
'    print(linha)\n')
'arq.close()\n')

'print("Contando linhas do arquivo")\n')
'cont = 0\n')
'arq = open("arquivo.txt","r")\n')
'for linha in arq:\n')
'    cont+=1\n')
'print("Numero de linhas no arquivo: ",cont)\n')
'arq.close()\n')

'print("Retorna apenas as linhas com a palavra python:")\n')
'cont=0\n')
'arq = open("arquivo.txt","r")\n')
'for linha in arq:\n')
'    linha = linha.strip()\n')
'    if "Python" in linha:\n')
'        cont+=1\n')
'        print(linha)\n')
'print("Foram encontradas", cont, "linhas")\n')
'arq.close()\n')
'##fim da execução##\n')

'print("Veja um exemplo de Leitura de Arquivos")\n')

'arq = open("arq01.txt","w")\n')
'arq.write("Universidade do Estado do Amazonas")\n')
'arq.write("Fazendo arquivos de texto com Python")\n')
'arq.write("Documento criado para aulas de LP basica")\n')
'arq.close()\n')

'##Leitura do arquivo##\n')
'arq = open("arq01.txt","r")\n')
'for linha in arq:\n')
'    linha = linha.strip()\n')
'    print(linha)\n')
'arq.close()\n')

'##acrescentando algo no arquivo##\n'))
'texto = input("Digite: ")\n')
'arq = open("arq01.txt","a")\n')
'arq.write(texto + "\n")\n')
'print("Operador concluido do arquivo" + arq.name + " usando o mode de acesso" + arq.mode + )\n')
'arq.close\n')

'print("Texto:")\n')
'arq = open("arq01.txt","r")\n')
'for linha in arq:\n')
'    linha = linha.strip()\n')
'    print(linha)\n')
'arq.close()\n')
'##fim do programa##\n')
'##fim da aula 08##\n')
"""
T.insert(tk.END, quote)
tk.mainloop()
