import tkinter as tk

root = tk.Tk()
S = tk.Scrollbar(root)
T = tk.Text(root, height=15, width=200)
S.pack(side=tk.RIGHT, fill=tk.Y)
T.pack(side=tk.LEFT, fill=tk.Y)
S.config(command=T.yview)
T.config(yscrollcommand=S.set)
quote = """Prosseguindo...
"('Aula 04 - Aprofundando listas')\n")
"('listas servem para armazenamento de dados')\n")
"('Ex10.: Padrão de guardar notas')\n")

"nota1 = int(input('digite nota1: '))\n")
"nota2 = int(input('digite nota2: '))\n")
"nota3 = int(input('digite nota3: '))\n")
"print((nota1,nota2,nota3))\n")

"('peculiaridade1')\n")
"('Observe que valores sairam em cada posição')\n")
"##programando##\n")
"('1 = [0,0,0,0,0]')\n")
"('for i in range(7):')\n")
"('  1[i] = 7*i')\n")
"('(1)')\n")

"('peculiaridade2')\n")
"('indice negativo infere')\n")
"('ler a lista ao contrário')\n")
"##programando##\n")
"('>>>notas=[4.5,8.6,9,7.8,7]')\n")
"('>>>notas[-1]')\n")
"('7')\n")

"##proximos comandos##\n")
"('Comando slicing{operador}')\n")
"('gera uma sub-lista na lista quando feito em console')\n")
"('variável[ind1:ind2]')\n")
"('>>>notas[1.5, 8.4, 9, 5.8, 2, 39.09, 132]')\n")
"('>>>notas[1:4]')\n")
"('>>>notas[8.4,9,5.8,2]')\n")

"('##VOLTANDO PARA O FOR')\n")
"('faz a variavel de controle assumir todos os valores')\n")
"('Sintaxe:')\n")
"('for a in x:')\n")
"('   print(x)')\n")

"('Operador append')\n")
"('sintaxe: lista.append(item)')\n")
"('serve para: acrescentar algo na lista, combinar uma lista vazia')\n")

"print('Ex.11')\n")
"x = []\n")
"a = int(input('quantia de int: '))\n")
"for i in range(a):\n")
"    dado = int(input('notas: '))\n")
"    x.append(dado)\n")
"print(x)\n")

"('##operações matemáticas com listas')\n")
"('Somar listas(concatenação) gera outra --> concatenação{L1+L2=L3}')\n")
"('Ex.12')\n")
"L1 = input('escrever lista1: ')\n")
"L2 = input('escrever lista2: ')\n")
"print([L1]+[L2])\n")

"('##o operador (*) faz repetição')\n")
"('Ex.13')\n")
"x = input('escrever lista1: ')\n")
"print([5*x])\n")

"##outros metodos de operação##\n")
"('##lista.insert(indice,dado)')\n")
"('inseri a info antes do indice')\n")
"('Ex.14')\n")
"x = [input('escrever lista2: ')]\n")
"x.insert(0,'99')\n")
"print([x])\n")

"print('##del.lista[posição]')\n")
"print('remove o item escolhido')\n")
"print('Ex.15')\n")
"x = int(input['escrever lista3: '])\n")
"del x[input('digite a posiçao: ')]\n")
"print(x)\n")

"('del --> remove; mas elimina o num digitado')\n")
"('Ex.16')\n")
"x = int(input['escrever lista4: '])\n")

"x.remove(input('digite o num: '))\n")
"input('escreva x: ')\n")
"print([x])\n")

"('Inicialização de listas')\n")
"('vamos comprimir valores, construindo com 1 laço os valores')\n")
"('Ex.17')\n")
"x = [input('digite lista: ')]\n")
"a = 5*x\n")
"print(a)\n")
"##fim do capítulo de 04##\n")
"""
T.insert(tk.END, quote)
tk.mainloop()
