import tkinter as tk

root = tk.Tk()
S = tk.Scrollbar(root)
T = tk.Text(root, height=15, width=200)
S.pack(side=tk.RIGHT, fill=tk.Y)
T.pack(side=tk.LEFT, fill=tk.Y)
S.config(command=T.yview)
T.config(yscrollcommand=S.set)
quote = ("Ok, Aqui é onde começamos a jornada na programação\n"
         "('Aula 01e02 - Introdução ao Python e Entendendo Primeiros conceitos')\n"
         "\n"
         "(Variaveis, Numeros, Matematica Basica)\n"
         "(As variáveis são nomes que damos para referenciar valores ao longo do nosso programa)\n"
         "(Aqui dizemos que x e y são variáveis, eles primeiro armazenaram os valores)\n"
         "(e depois os usamos para calcular operçaões)\n"
         "\n"
         "('arq02.txt','w')\n"
         "(além disso mudamos o valor que y representava atribuindo a ele o valor 7.)\n"
         "(podem facilitar a interpretação de um programa.)\n"
         "\n"
         "(Uma breve observação sobre variáveis em Python)\n"
         "(Variáveis servem para o programa reservar espaço na memoria para um determinado tipo de informação)\n"
         "(tudo em Python são objetos, então, as variáveis Python armazenam uma referência a um objeto.)\n"
         "\n"
         "(Como representar as variáveis)\n"
         "\n"
         "(podem possuir caracteres numéricos.)\n"
         "(não podem ter espaço entre elas)\n"
         "(não podem começar com números)\n"
         "(não podem ter caracteres de acentuação tais como ^, ~, !)\n"
         "(não podem ter caracteres especiais como @, & nem hifens)\n"
         "(determina vários métodos especiais e variáveis que usam esse padrão)\n"
         "(Na tabela abaixo exemplos de nomes validos e inválidos)\n"
         "\n"
         "(Nomes de variáveis validos e inválidos)\n"
         "(area_triangulo' - 'area triangulo' #não é permitido espaço em branco)\n"
         "(samuel_john ou samuel_&_john (não são validos caracteres especiais))\n"
         "(_inicio total-val (não são valido hifens))\n"
         "(Por fim, Python diferencia nomes de variáveis)\n"
         "(com letras maiúsculas e minúsculas exemplo: AREA, Area e area são 3 variáveis diferentes)\n"
         "\n"
         "(Operadores Aritméticos no Python)\n"
         "(+ - soma\n)\n"
         "(– - subtração)\n"
         "(* - multiplicação)\n"
         "(/ - divisão)\n"
         "(// - Divisão trunca a parte fracionaria)\n"
         "(% - Produz o resto da divisão)\n"
         "(** - Exponenciação)\n"
         "\n"
         "(Operadores de comparação no Python)\n"
         "(abs(x) - Retorna o valor absoluto de x)\n"
         "(pow(x, y) - O mesmo x**y)\n"
         "(round(x, n) - Retorna um int ou float)\n"
         "\n"
         "(Operadores de Descrição no Python)\n"
         "( < - menor que)\n"
         "(<= - menor ou igual a)\n"
         "( > - maior que)\n"
         "(>= - maior ou igual a)\n"
         "(== - igual)\n"
         "(!= - diferente)\n"
         "\n"
         "(Operadores Lógicos no Python)\n"
         "(and P and Q - Resulta 'True' só se P e Q forem verdade)\n"
         "(or P or Q   - Resulta 'False' só se P ou Q forem falsos; se não retorna True)\n"
         "(not P Se P  - Resulta 'False' se P é falso; se não retorna True)\n"
         "##fim das aulas 1 e 2##\n")
T.insert(tk.END, quote)
tk.mainloop()
